--- #YAML:1.0
name:               mmm
version:            0.43
abstract:           ~
author:
    - Olivier Thauvin <nanardon@nanardon.zarb.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:               ~
    Config::IniFiles:  ~
    Date::Calc:        ~
    Digest::MD5:       ~
    File::Temp:        ~
    IO::Select:        ~
    Mail::Send:        ~
    Net::DNS:          ~
    URI:               ~
    WWW::HostipInfo:   ~
    XML::Simple:       ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
